name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch to trigger deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'  # Set your Ruby version here

    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Build and deploy
      uses: jekyll/actions-pages@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
